#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Discrete Mathematics documentation build configuration file, created by
# sphinx-quickstart on Sat Jan 27 09:02:45 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
                'sphinx.ext.githubpages'
              , 'sphinx.ext.imgmath'
              , 'sphinx.ext.graphviz'
              , 'lean_sphinx'
              , 'sphinx.ext.todo'
]

# Enable ToDos to be embedded in generated text. Turn off for production.
todo_include_todos=True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Discrete Mathematics: A Computational Approach'
copyright = u'2018, Kevin Sullivan'
author = u'Kevin Sullivan'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.2'
# The full version, including alpha/beta/rc tags.
release = u'0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# use numbering for section references with :numref:, e.g. 'Section 3.2'.
numfig = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'
#html_theme = 'classic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
#    "collapsiblesidebar": "true",
#    "stickysidebar": "true",
    "logo_name": True,
    "font_family": "Times New Roman, Times, serif",
    "head_font_family": "Times New Roman, Times, serif",
    "code_bg": "white",
    "extra_nav_links": {"PDF version":"discrete_mathematics.pdf",
                        "Lean Home":"https://kevinsullivan.github.io/cs-dm"},
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# kevin: include?
# html_output_encoding = 'ascii'


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'about.html',
        'navigation_without_header.html',
        #'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
        #'donate.html',
    ]
}

#kevin: original
#html_sidebars = {
#    '**': [
#        'relations.html',  # needs 'show_related': True theme option to display
##        'searchbox.html',
#    ]
#}


# kevin: why right here?
imgmath_latex_preamble = r"""
\usepackage{amsmath}
\usepackage{turnstile}
\usepackage{bussproofs}
\usepackage{prftree}
\usepackage{cases}
"""

# -- Options for HTMLHelp output ------------------------------------------
htmlhelp_basename = 'discrete_math'

# Output file base name for HTML help builder.
htmlhelp_basename = 'discrete_math'


# -- Options for LaTeX output ---------------------------------------------

# sullivan
latex_engine = 'xelatex'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',


    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    'preamble': r"""
    \usepackage{amsmath}
    \usepackage{cases}
    \usepackage{turnstile}
    \usepackage{prftree}
    """,

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'discrete_math.tex', u'Mathematical Logic: A Computational Approach',
     u'Kevin Sullivan', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mathematical_logic', u'Mathematical Logic: A Computational Approach',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'mathematical_logic', u'Mathematical Logic: A Computational Approach',
     author, 'discrete_math', 'Discrete mathematics through automated formal methods.',
     'Miscellaneous'),
]



# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']





